name = "Splines"
uuid = "59274c38-6050-4eab-b485-1b2b36df4d3b"
authors = ["Henry Gebhardt <gebhardt@caltech.edu> and contributors"]
version = "0.2.3"

[compat]
julia = "1"

[extras]
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
PythonPlot = "274fc56d-3b97-40fa-a1cd-1b4a50311bf9"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Dierckx", "Profile", "PythonPlot", "Random", "Statistics", "Test"]
